### ISSUE TITLE
Repo di programmazione personale

### ISSUE THREAD

**Issue by foxyseta** [csunibo/programmazione#1]
Ciao! Io ricordo che feci molti esercizi in C++ (tutti quelli sui lucidi del mio anno + alcuni del libro + il mio scritto + un lab) e che li misi nella mia repo personale https://github.com/FoxySeta/unibo-00819-programmazione. Erano tutti compilanti e funzionanti. Se serve siete liberi di fare copia e incolla. Se non vi piace lo stile C++ (non molto cosimo-style, a parte il mio scritto), potete anche non usare niente.

**Comment by foxyseta** [comment]
Considerazioni analoghe si possono fare per le mie repo su architettura (tutti i progetti funzionanti!) e logica (esercizi Haskell a lezione) quando questi insegnamenti saranno resi disponibili dagli studenti di @csunibo/primo-anno.

**Comment by Flecart** [comment]
Sì, grazie mille. Sarebbe molto comodo poterlo fare, questo pomeriggio provo ad aggiornare questa repo.

**Comment by foxyseta** [comment]
Volendo posso aprire una pr e poi se ti piace la mergi, sennò faccio modifiche.
